HAI 1.2

  I HAS A NUMBARONE
  I HAS A NUMBARTWO

  
  VISIBLE "give me first number"
  GIMMEH NUMBARONE
  NUMBARONE IS NOW A NUMBAR

  VISIBLE "now give second nnumber"
  GIMMEH NUMBARTWO
  NUMBARTWO IS NOW A NUMBAR

 VISIBLE SUM OF NUMBARONE AN NUMBARTWO

KTHXBYE